services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_9745156203d5_key -iv $encrypted_9745156203d5_iv
  -in travis_deploy_rsa.enc -out travis_deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_9745156203d5_key -iv $encrypted_9745156203d5_iv
  -in id_rsa_insa_training.enc -out ~\/.ssh/id_rsa_insa_training -d
- sudo service mysql stop
- docker pull takimatraining/devops-training-db
- docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db
# Prepare deploy
  - openssl aes-256-cbc -K $encrypted_xxxxxxx_key -iv $encrypted_xxxxxxxxxxx_iv
    -in travis_deploy_rsa.enc -out ~\/.ssh/travis_deploy_rsa -d  # Généré par travis encrypt-file
  - chmod 600 /tmp/travis_deploy_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add /tmp/travis_deploy_rsa
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config



script:
- |
  mvn clean install sonar:sonar \
  -Dsonar.projectKey=cporiel_sample-application-students \
  -Dsonar.organization=cporiel-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=$SONAR_TOKEN
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=cporiel/sample-application
- docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
- docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME:$TAG
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: bkxXU/Rxft8bHBKBJfUi7jplPNbe+K41fj+z472THIwGkNhL7qC3pADqHbmaCfAQCmfxUVQGMHu6WtGKjzpchb+szWX/cVAw6WoIw4kOEmIQBWagcV84n8lW2xlO3+tWDXfS/e0hNRMBhbGKVNcmeJ/6CN641+ZhKfd+kzydFj/uHjFJopKf6SBYK7fHPyPBs5cO0k8zcJVYukjzJaUSRFLIzNBb3Zt3qVPUVLLXHTMYwqlcHBNWJXABqagZyh0VsAx67RSEZs+mD21VoXhyURXEccLPLJiBFjJMQwfxDNJgUZoUDdyDZabsNxU+5vUIbjUh1X3blikqO9SqTBygbXnxeIXxHpVWwh4MRL9NY+RNysmilmedZ7iui1nZ6ZyqeZwi9O8KvL32w5Ke/a6V94q1LyYwZ9YThI2jiwK7ttcAlb/RMTzPqxggc6hXKf989DAmof/2y3cHKRxQ0Fc9mYV7dxHRtkK0yopwHeKjZaHVsLdoF/QhjFoKlA5744f25lM2biOx9sCyiMQvP5Euph4ixEyppt24I1IkrpZezUaEyD4x9QOVPHFoLRNxAw6Io56z5lfGsCzxWdu3DaBxjslbVwOR3+ninBMHCfSmA2y6WvFUQFEZqqMZfkIhwZnJfhMWOtlPSXXFyO8Ti9z2gbsV1+GF07LO8uUc3jqQLdw=
  - secure: RD8elBMR/vbLAssB+ZXotQjSS0YsZbBr0EJ/c01ou+ASa2Ht+yuqhWz21sHkpnwD/DSvtP7dp3vs7XWqHrdCqchPq5Gmkk69+j9k+rVZPvrV4S+ZymU1YFttxxxffHDu5yDvA37/D3+PdVbhYxBK9sYimOghwJCiIEjhyt/gS0FTOEiodrF1lKnywHrjQ2DOpE+PeSz6lWK5u6hgb1bZUN0JyAOdDdtqm8mQqE8b152xSbHXvCJXR48K8mdk+Pwo6v4lhjhgngj4tpabM1uufNLb1pxyuidGvFvXSUkMb8hhsTs1cHfwLskhsKKMLMTfz+tn0EeGaKsSfHyFjb7sxPS/dsOw5R7GYP8eqvheX6XEwxbNkW66hZeH8BA6tWeC8n4mN9fa5fsDol9lQ3n06Fsdm+nwaO4DqARpStpmZpXKnCdwPcJhKQ3J3hjDn1UMBOYud8M5qhM+ySnODI+q5sbJKEMAvdNCVVesfOWRvSDD/qp7BijbEklEnlNLf7J1Sp3V+6ga3ylJHlp8y7wh/5oCks1FCHuixk14wVEpsZ9+ND3fhSY5H46+GpjXjcPzXvdVbpMP3hZkW1eqBwma6m6pUASWFmz+nHlM1cWfC3HNkVCnMUFDjj027Q3yNTHa99KzF8eOiuVrHiG0LInQ4S9wuNLPnEalfKrKps3FhLg=
  - secure: l6sUNlz+jx5P0hDXSHeUV3lmtpeoqGmMacivdqRGPlJ1o8LHx52nad5QD5uY5YGhr4TFHI03c+Jrai0YfjynzQiWd/FsGbAoZ8BjV2v8pC5NqOQz8jGDK5olQOCElQyEasRCuhJnhPqrZjbOt8KPQrR/b+oZfc/U7CZxHOA2/DvrCPNMxv/QASP76JPc9P5wgK9ZBSpdievstwUzetflcViKtHulUk9W2cVKEMUkztUsIG5QvWvIc+SoyNwt2R2P5tB4/914KdoNdVfg8eAvn+azGJazMdMh7I4XAVvRK9Gpr4fKy+YQEid8FBDeA5P5VqecgTT+GjogH9AuvUkgL52V8Yt4FWAUH8T8cvl4hSpUVctJdZiiVk9gkFpPTMSUlrNz4vbZhrmQK3CFrNZyGZUcjytLSAjp+JP1FKW/16rUuGUnUW7QWQCpcCl0QyVPdv/zM42llOzRw8qalp30CukoUnmysxinSjDCrOH5fTKjkZltn/iWgN9LfKqYzZ7DOaYS8WaUq3WlVLZLXqEHHZx+q3sXZlvZS4ZV8IScrEY9qAK17xRsP89iwDZHL4DLfUDvRyGGBi+1LuiaGh41BdB1DaIW3CqUGNJeQ0otBJyFeC0W09BN/1hRMoC8TDv2KvZ2vuCFr7PcRd9B47LFhBbZtHFdD0ek207DmhOWewI=
   - secure: q7D7dcmDf9+Uh61cwzj1C9sVJUfJ98smg8/kbG+Iqyo3oJxAld2QsxKlk3PPlYsKIc9z9kwHJkE/Hc6JBAO0Yo7HrJoXUPpZG3W3BnWo2LX1HxWcfGyK64hv/VIInmrJD7wLyfUYHRxtp+lxgmILDi903v1JWNL3ccwoQejYyN+Kx+Ry53el7dHDVNxff1Vy3KKRxOc3iKJdI+MOSp+L4Y7F04uxMZ1XverDRlmx94bPO8Oo5s7fQz83tso+FQZD9agJL1oM95GAt3kiLTK3/2DDgirAxNF0VEGFvw+JXHgpmd3fDTjyFQqUB5hyummnqbt74Fif6LySYwh19bjjLP3Z+/v3vd2M+phGDMeT3CLZmmCKO8/8xodtJRO5QA4NfkRDUxZ8YVVg0aj0Ns/dWcfG8ujUhbSbrtQnWs05RE/ijD6jYdyDB0dKEE9ljky0uS/8RwN5MsCiNK0Z6l5vzWhyLiAvREMQwzzPLph7A1SyykHk/+8JQxSqahL/uj2xaOiGSfhyFBKu+N4zeQKrpS8xSa48eOgVTJ8iF+LPr5o/1lX8/sEyfnuAFG93HB9gleEdXqQYYK2eKXYmBCxNFtQoqrHBKiSU28EH5bIfTb3/1L6nmzoatq3lgWKSyVZCR2I5cBnl/O5TvX22P05vuWqDYPnYA/sOLEp4VcY7rq4=
   - secure: QjZiy4Yli964AJMDZZY5TpocHJEBNd6zzA3jvOt4RynoiuCXKwianNv0TLVnAuryiVJSgaUom8EfDXzu7hnExMvbJwJHkW3/O36vem3X+r0sFSGBDLugRYzN7M3yQ95wk9gQnZ6fpZ+3wmZZDtH36UmX/CYpk643lN5xqYFrPeYyrLYMmj9vy2dWZa8GDNhflRsajanSZmzeAbD7BpzJtNmsiQhnNe5yItx1mp7utVqyntYHQD4i7cZMq94L3xyufrPa1hj/ImZPvX7rEuGntj6qoQs12XswEWjymiZDxHfXn5RvAVlpH0Wo+RGe+imHjSWWUzTju0TvmAit+YM4oGnqJpLTF0Yv3PQbGayYKfAv5G8xytDob65KRUA1SvyPWXUafEhia9rLaXNl8pm2ds8QXHkx0UbCPVIBOR0H5AUR9tyhsYz8knbZI/6WE654c//YGgWgjlOR4siU3fJfeWc7yhPy4xp5APJYli94ETDzWAy+H1gdLAnd/yo0axLIPfgXbIOTqXePJk8bNAODPEkE7rrmoF/sqonehsWP99PSInUpQ8kaDcAGiaQU4ceH2vCemUZOcwJ5cCU/zDqMOZT3me8F3YFdpbNOIZgkTBIb1fuoCwAYvGxqzqeQ49E8dhB5hyBlTcCWwOcFd97TCib5JhQLOOVfcHlsEmHvtAU=





deploy:
  provider: script
  script: ssh -i /tmp/travis_deploy_rsa $DEPLOY_USER@$SERVER_IP_ADDRESS "sudo docker pull $IMAGE_NAME:$TAG && sudo docker rm -f app || true && sudo docker run -d --network net -p 80:8080 --name app $IMAGE_NAME:$TAG"
  on:
    branch: master
