# Define the services to use
services:
  - docker

before_install:
  - sudo service mysql stop
  - docker pull takimatraining/devops-training-db
  - docker run -d -p 127.0.0.1:3306:3306 takimatraining/devops-training-db

# Run Unit Test and Integration Tests
#script:
#  - mvn verify
# Cache the .m2 folder to prevent redownloading dependencies on each build

# The pipe (|) is useful to create multiline scripts
script:
  - |
    mvn clean install sonar:sonar \
    -Dsonar.projectKey=cporiel_sample-application-students \
    -Dsonar.organization=cporiel-github \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
  - "$HOME/.m2/repository"

# Environment variables are strings (double quotes)
# Example:
# - secure: "DpR1th9rZvLMX0......"
env:
  global:
    - secure: "bkxXU/Rxft8bHBKBJfUi7jplPNbe+K41fj+z472THIwGkNhL7qC3pADqHbmaCfAQCmfxUVQGMHu6WtGKjzpchb+szWX/cVAw6WoIw4kOEmIQBWagcV84n8lW2xlO3+tWDXfS/e0hNRMBhbGKVNcmeJ/6CN641+ZhKfd+kzydFj/uHjFJopKf6SBYK7fHPyPBs5cO0k8zcJVYukjzJaUSRFLIzNBb3Zt3qVPUVLLXHTMYwqlcHBNWJXABqagZyh0VsAx67RSEZs+mD21VoXhyURXEccLPLJiBFjJMQwfxDNJgUZoUDdyDZabsNxU+5vUIbjUh1X3blikqO9SqTBygbXnxeIXxHpVWwh4MRL9NY+RNysmilmedZ7iui1nZ6ZyqeZwi9O8KvL32w5Ke/a6V94q1LyYwZ9YThI2jiwK7ttcAlb/RMTzPqxggc6hXKf989DAmof/2y3cHKRxQ0Fc9mYV7dxHRtkK0yopwHeKjZaHVsLdoF/QhjFoKlA5744f25lM2biOx9sCyiMQvP5Euph4ixEyppt24I1IkrpZezUaEyD4x9QOVPHFoLRNxAw6Io56z5lfGsCzxWdu3DaBxjslbVwOR3+ninBMHCfSmA2y6WvFUQFEZqqMZfkIhwZnJfhMWOtlPSXXFyO8Ti9z2gbsV1+GF07LO8uUc3jqQLdw="





